Repository codeit-bootcamp-spring/2-sprint-mission, pull requests merged in 2025-07, with the labels that each got.

#324 [김보경] sprint9
  .github/PULL_REQUEST_TEMPLATE.md
  META-INF/MANIFEST.MF
  build.gradle
  src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  src/main/java/com/sprint/mission/discodeit/config/ChannelSecurity.java
  src/main/java/com/sprint/mission/discodeit/config/SecurityConfig.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/api/AuthApi.java
  src/main/java/com/sprint/mission/discodeit/dto/data/CsrfTokenDto.java
  src/main/java/com/sprint/mission/discodeit/dto/data/UserDto.java
  src/main/java/com/sprint/mission/discodeit/dto/request/UserRoleUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/entity/BinaryContent.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/entity/UserRole.java
  src/main/java/com/sprint/mission/discodeit/entity/UserStatus.java
  src/main/java/com/sprint/mission/discodeit/security/AdminInitializer.java
  src/main/java/com/sprint/mission/discodeit/security/CustomLoginFailureHandler.java
  src/main/java/com/sprint/mission/discodeit/security/CustomLoginSuccessHandler.java
  src/main/java/com/sprint/mission/discodeit/security/CustomUserDetailsService.java
  src/main/java/com/sprint/mission/discodeit/security/JsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/sprint/mission/discodeit/security/LogoutAuthenticationFilter.java
  src/main/java/com/sprint/mission/discodeit/security/UserPrincipal.java
  src/main/java/com/sprint/mission/discodeit/service/AuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicAuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/resources/application.yml
  src/main/resources/fe_bundle_1.2.3.zip
  src/main/resources/schema.sql
  src/main/resources/static/assets/index-BdLer33P.js
  src/main/resources/static/assets/index-CT7m21vd.js
  src/main/resources/static/index.html
Labels: 순한맛🐑

#312 [이유나] sprint9
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/sprint/mission/discodeit/config/AdminAccountInitializer.java
  src/main/java/com/sprint/mission/discodeit/config/SecurityConfig.java
  src/main/java/com/sprint/mission/discodeit/config/SwaggerConfig.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/controller/api/AuthApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/MessageApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/ReadStatusApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/UserApi.java
  src/main/java/com/sprint/mission/discodeit/dto/data/UserDto.java
  src/main/java/com/sprint/mission/discodeit/dto/data/UserStatusDto.java
  src/main/java/com/sprint/mission/discodeit/dto/request/RoleUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/UserStatusCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/UserStatusUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/entity/Role.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/entity/UserStatus.java
  src/main/java/com/sprint/mission/discodeit/exception/userstatus/DuplicateUserStatusException.java
  src/main/java/com/sprint/mission/discodeit/exception/userstatus/UserStatusException.java
  src/main/java/com/sprint/mission/discodeit/exception/userstatus/UserStatusNotFoundException.java
  src/main/java/com/sprint/mission/discodeit/mapper/UserMapper.java
  src/main/java/com/sprint/mission/discodeit/mapper/UserStatusMapper.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/ReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/security/CustomLoginFailureHandler.java
  src/main/java/com/sprint/mission/discodeit/security/CustomLoginSuccessHandler.java
  src/main/java/com/sprint/mission/discodeit/security/CustomLogoutFilter.java
  src/main/java/com/sprint/mission/discodeit/security/CustomUserDetails.java
  src/main/java/com/sprint/mission/discodeit/security/CustomUserDetailsService.java
  src/main/java/com/sprint/mission/discodeit/security/JsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/sprint/mission/discodeit/service/AuthService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/ReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/UserStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicAuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserStatusService.java
  src/main/java/com/sprint/mission/discodeit/storage/s3/S3BinaryContentStorage.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
  src/main/resources/schema.sql
  src/main/resources/static/assets/index-BBB7Nxw7.js
  src/main/resources/static/assets/index-BdLer33P.js
  src/main/resources/static/index.html
  src/test/java/com/sprint/mission/discodeit/repository/UserStatusRepositoryTest.java
  src/test/java/com/sprint/mission/discodeit/storage/s3/AWSS3Test.java
  src/test/java/com/sprint/mission/discodeit/storage/s3/S3BinaryContentStorageTest.java
Labels: 매운맛🔥

#330 [이경빈] sprint9
  build.gradle
  src/main/java/com/sprint/mission/discodeit/config/DaoAuthenticationProviderConfig.java
  src/main/java/com/sprint/mission/discodeit/config/PasswordEncoderConfig.java
  src/main/java/com/sprint/mission/discodeit/config/SecurityConfig.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/api/AuthApi.java
  src/main/java/com/sprint/mission/discodeit/dto/request/UserRoleUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/entity/Role.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/exception/ErrorCode.java
  src/main/java/com/sprint/mission/discodeit/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/exception/security/SecurityException.java
  src/main/java/com/sprint/mission/discodeit/exception/security/SessionExpiredException.java
  src/main/java/com/sprint/mission/discodeit/exception/user/InvalidCredentialsException.java
  src/main/java/com/sprint/mission/discodeit/mapper/UserMapper.java
  src/main/java/com/sprint/mission/discodeit/security/AdminInitializer.java
  src/main/java/com/sprint/mission/discodeit/security/CustomSessionInformationExpiredStrategy.java
  src/main/java/com/sprint/mission/discodeit/security/CustomUserDetails.java
  src/main/java/com/sprint/mission/discodeit/security/SecurityMatchers.java
  src/main/java/com/sprint/mission/discodeit/security/SessionRegistryLogoutHandler.java
  src/main/java/com/sprint/mission/discodeit/security/UserDetailService.java
  src/main/java/com/sprint/mission/discodeit/security/filter/JsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/sprint/mission/discodeit/security/filter/LogoutFilter.java
  src/main/java/com/sprint/mission/discodeit/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/sprint/mission/discodeit/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/sprint/mission/discodeit/service/AuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicAuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/main/resources/schema.sql
  src/main/resources/static/assets/index-CT7m21vd.js
  src/main/resources/static/index.html
  src/test/java/com/sprint/mission/discodeit/storage/s3/AWSS3Test.java
  whiteimage.png
  whiteimage2.png
Labels: 매운맛🔥, 지각제출⏰

#315 [선혜린] sprint9
  build.gradle
  src/main/java/com/sprint/mission/discodeit/config/SecurityConfig.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/controller/api/AuthApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/UserApi.java
  src/main/java/com/sprint/mission/discodeit/dto/data/UserDto.java
  src/main/java/com/sprint/mission/discodeit/dto/request/RoleUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/entity/Role.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/entity/UserStatus.java
  src/main/java/com/sprint/mission/discodeit/exception/user/InvalidCredentialsException.java
  src/main/java/com/sprint/mission/discodeit/exception/userstatus/DuplicateUserStatusException.java
  src/main/java/com/sprint/mission/discodeit/exception/userstatus/UserStatusException.java
  src/main/java/com/sprint/mission/discodeit/exception/userstatus/UserStatusNotFoundException.java
  src/main/java/com/sprint/mission/discodeit/mapper/UserMapper.java
  src/main/java/com/sprint/mission/discodeit/mapper/UserStatusMapper.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/ReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/security/CustomLoginFailureHandler.java
  src/main/java/com/sprint/mission/discodeit/security/CustomLoginSuccessHandler.java
  src/main/java/com/sprint/mission/discodeit/security/CustomSessionInformationExpiredStrategy.java
  src/main/java/com/sprint/mission/discodeit/security/CustomUserDetails.java
  src/main/java/com/sprint/mission/discodeit/security/DataInitializer.java
  src/main/java/com/sprint/mission/discodeit/security/DatabaseUserDetailsService.java
  src/main/java/com/sprint/mission/discodeit/security/JsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/sprint/mission/discodeit/security/SecurityMatchers.java
  src/main/java/com/sprint/mission/discodeit/security/SessionInvalidateLogoutHandler.java
  src/main/java/com/sprint/mission/discodeit/service/AuthService.java
  src/main/java/com/sprint/mission/discodeit/service/UserStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicAuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserStatusService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/main/resources/schema.sql
  src/main/resources/static/assets/index-BdLer33P.js
  src/main/resources/static/assets/index-kQJbKSsj.css
  src/main/resources/static/index.html
  src/test/java/com/sprint/mission/discodeit/controller/UserControllerTest.java
  src/test/java/com/sprint/mission/discodeit/repository/MessageRepositoryTest.java
  src/test/java/com/sprint/mission/discodeit/repository/ReadStatusRepositoryTest.java
  src/test/java/com/sprint/mission/discodeit/repository/UserRepositoryTest.java
  src/test/java/com/sprint/mission/discodeit/repository/UserStatusRepositoryTest.java
  src/test/java/com/sprint/mission/discodeit/service/basic/BasicUserServiceTest.java
  src/test/java/com/sprint/mission/discodeit/service/basic/BasicUserStatusServiceTest.java
Labels: 순한맛🐑

#368 [정종현] sprint11
  build.gradle
  src/main/java/com/sprint/mission/discodeit/config/AsyncConfig.java
  src/main/java/com/sprint/mission/discodeit/config/ContextTaskDecorator.java
  src/main/java/com/sprint/mission/discodeit/config/MetricsConfig.java
  src/main/java/com/sprint/mission/discodeit/config/RetryConfig.java
  src/main/java/com/sprint/mission/discodeit/controller/NotificationController.java
  src/main/java/com/sprint/mission/discodeit/dto/data/AsyncTaskFailure.java
  src/main/java/com/sprint/mission/discodeit/dto/data/NotificationDto.java
  src/main/java/com/sprint/mission/discodeit/dto/request/ReadStatusUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/entity/BinaryContent.java
  src/main/java/com/sprint/mission/discodeit/entity/BinaryContentUploadStatus.java
  src/main/java/com/sprint/mission/discodeit/entity/Notification.java
  src/main/java/com/sprint/mission/discodeit/entity/NotificationType.java
  src/main/java/com/sprint/mission/discodeit/entity/ReadStatus.java
  src/main/java/com/sprint/mission/discodeit/event/NotificationEvent.java
  src/main/java/com/sprint/mission/discodeit/event/NotificationEventListener.java
  src/main/java/com/sprint/mission/discodeit/mapper/NotificationMapper.java
  src/main/java/com/sprint/mission/discodeit/repository/NotificationRepository.java
  src/main/java/com/sprint/mission/discodeit/service/NotificationService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicAuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicBinaryContentService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicNotificationService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/storage/local/LocalBinaryContentStorage.java
  src/main/java/com/sprint/mission/discodeit/storage/s3/S3BinaryContentStorage.java
  src/main/resources/application.yaml
Labels: 미완성🛠️, 순한맛🐑

#367 [공한나] sprint11
  build.gradle
  docker-compose.yml
  src/main/java/com/sprint/mission/discodeit/config/AsyncConfig.java
  src/main/java/com/sprint/mission/discodeit/config/CacheConfig.java
  src/main/java/com/sprint/mission/discodeit/config/KafkaConsumerConfig.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/NotificationController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/domain/AsyncTaskFailure.java
  src/main/java/com/sprint/mission/discodeit/domain/BinaryContent.java
  src/main/java/com/sprint/mission/discodeit/domain/BinaryContentUploadStatus.java
  src/main/java/com/sprint/mission/discodeit/domain/Notification.java
  src/main/java/com/sprint/mission/discodeit/domain/NotificationType.java
  src/main/java/com/sprint/mission/discodeit/domain/ReadStatus.java
  src/main/java/com/sprint/mission/discodeit/dto/NotificationDto.java
  src/main/java/com/sprint/mission/discodeit/dto/request/ReadStatusUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/event/BinaryContentUploadedEvent.java
  src/main/java/com/sprint/mission/discodeit/event/NotificationEvent.java
  src/main/java/com/sprint/mission/discodeit/event/handler/BinaryContentEventHandler.java
  src/main/java/com/sprint/mission/discodeit/event/handler/NotificationEventHandler.java
  src/main/java/com/sprint/mission/discodeit/event/kafka/KafkaEventPublisher.java
  src/main/java/com/sprint/mission/discodeit/event/kafka/NotificationKafkaEventConsumer.java
  src/main/java/com/sprint/mission/discodeit/mapper/NotificationMapper.java
  src/main/java/com/sprint/mission/discodeit/repository/AsyncTaskFailureRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/NotificationRepository.java
  src/main/java/com/sprint/mission/discodeit/service/NotificationService.java
  src/main/java/com/sprint/mission/discodeit/service/async/AsyncBinaryContentService.java
  src/main/java/com/sprint/mission/discodeit/service/async/BinaryContentProcessor.java
  src/main/java/com/sprint/mission/discodeit/service/async/SyncBinaryContentService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicAuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicNotificationService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/util/FileUtils.java
  src/main/java/com/sprint/mission/discodeit/util/SecurityUtils.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/main/resources/static/assets/index-BDMoC4ds.js
  src/main/resources/static/assets/index-BTN3rKEm.js
  src/main/resources/static/index.html
Labels: 매운맛🔥
